### ISSUE TITLE
Connection error

### ISSUE THREAD

**Issue by erickfung** [hanahaneull/Discord-MultiLogin#1]
Hi

How can I fix the error below?

`C:\Discord-MultiLogin-master> node discordClient.js
(node:20004) UnhandledPromiseRejectionWarning: Error: Incorrect login details were provided.
    at WebSocketConnection.<anonymous> (C:\Discord-MultiLogin-master\node_modules\discord.js\src\client\ClientManager.js:48:41)
    at Object.onceWrapper (events.js:417:26)
    at WebSocketConnection.emit (events.js:310:20)
    at WebSocketConnection.onClose (C:\Discord-MultiLogin-master\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:390:10)
    at WebSocket.onClose (C:\Discord-MultiLogin-master\node_modules\ws\lib\event-target.js:124:16)
    at WebSocket.emit (events.js:310:20)
    at WebSocket.emitClose (C:\Discord-MultiLogin-master\node_modules\ws\lib\websocket.js:191:10)
    at TLSSocket.socketOnClose (D:\Downloads\Discord-MultiLogin-master\node_modules\ws\lib\websocket.js:850:15)
    at TLSSocket.emit (events.js:322:22)
    at net.js:672:12
(node:20004) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:20004) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

Thanks!

**Comment by hanahaneull** [comment]
2 possibility:

1. Installing discord.js package higher than 11.6.4.
2. Wrong/invalid token.
